services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta de comunicação AMQP
      - "15672:15672" # Porta da interface de gerenciamento web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    restart: always